### ISSUE TITLE
Sprint 2 - Release

### ISSUE THREAD

**Issue by LPOdev** [CPNV-ES-RIA2/LUIS#2]
Ceci est une release incomplete du [Sprint 2](https://icescrum.cpnv.ch/p/ESRIA2/#/planning/3908/sprint/3910).

Le point d'entrée est la branche de la feature, publiée à l'aide de GitFlow: https://github.com/CPNV-ES-RIA2/LUIS/tree/feature/s3-frontend-conception-and-tests.

# Story 3 - Frontend - offline mode - concept + tests

Avant de commencer à coder, j'ai créé les différents fichiers de tests pour les components que j'estimais utiliser.
Ces tests sont trouvables à l'intérieur du fichier `__tests__`, dans le même dossier où se trouve le component dans le projet `lpo-vision`.

Tests:

- `components/layout/__tests__`, pour le test du header.
- `components/__tests__`, pour le test du dropdown qui permet de changer de langue.
- `views/analyses/__tests__`, pour le test du formulaire d'analyse et de l'affichage des résultats.

Je ne suis pas très satisfait de mon rendu, il y a largement beaucoup d'amélioration à faire au niveau du code (bonnes pratiques, emplacement, etc) mais après réflexion, il est préférable d'avoir un avis extérieur pour savoir si je suis dans la bonne voie ou pas.

# Story 4 - Learn more about test strategies

Pour mes tests, je me suis appuyé sur:

- [Vitest](https://vitest.dev/)
- [Vue Test Utils](https://test-utils.vuejs.org/)
- [Happy Dom](https://www.npmjs.com/package/happy-dom)

**Comment by lpodev** [comment]
Bonjour,

Désolé pour le retard, voici le point d'entrée de la mise à jour pour le SPRINT 2:
https://github.com/CPNV-ES-RIA2/LUIS/commit/789360432d2c9112e975042c0678a3aeb9932213
