### ISSUE TITLE
Sprint 3 - Release

### ISSUE THREAD

**Issue by LPOdev** [CPNV-ES-RIA2/LUIS#3]
Je n'ai rien à vous rendre actuellement concernant les stories du [Sprint 3](https://icescrum.cpnv.ch/p/ESRIA2/#/planning/3908/sprint/3911). Je ne suis pas bloqué, j'ai pris du retard dans les sprints précédents et je fais au plus vite pour tout rattraper. J'estime avoir tout récupéré d'ici à la fin de la semaine.

**Comment by lpodev** [comment]
Comme dit en classe, j'ai eu un petit soucis de comprehension de ce qui était réellement attendu au Sprint 2 et 3.
Dans mon Sprint 2, j'ai effectué les deux ce qui fait que mon point d'entrée du rendu du Sprint 3 est le même que le Sprint 2.

Le voici: https://github.com/CPNV-ES-RIA2/LUIS/commit/789360432d2c9112e975042c0678a3aeb9932213

**Comment by NicolasGlassey** [comment]
@lpodev 

J'ai bien pris note de vos trois issues. Mais pourquoi avoir tout livré dans la branche main ?
