### ISSUE TITLE
Final Release

### ISSUE THREAD

**Issue by LPOdev** [CPNV-ES-RIA2/LUIS#4]
Bonjour, 

Voici ma livraison finale pour le projet RIA2.

## Backend

J'ai pu finaliser la dockerisation de mes microservices + monorepo, mais malheuresement pas assez de temps pour l'implémenter avec le frontend.

La documentation a été mise à jour sur la branche develop leur repository ([BI-Project](https://github.com/lpodev/BI-Project/tree/develop)). Voici le lien vers le point d'entrée (dernier commit): https://github.com/lpodev/BI-Project/commit/82e10c7c3d1184b6738cf65212473bb878e391f2.

## Frontend

J'ai complete la documentation et ajouté un Wiki complet au projet depuis la dernier release.

L'application est actuellement fonctionnel (sans le contact api) avec tous les tests qui passent.

Je n'ai malheureusement pas eu assez de temps pour faire le docker proprement, comme on avait discuté ce matin. Il y du multistaging mais il y a des incohérences entre les deux (la version d'os, par exemple).

Voici le lien vers la release GitFlow: https://github.com/CPNV-ES-RIA2/LUIS/commit/8826d6f479343467e8d5e5025333846a0defeb25

## Conclusion

Je reste déçu ne pas être arrivé au bout du projet, mais je reste satisfait d'avoir réussi à avoir un backend propre et prêt à être intégré au frontend. Je pense que la vidéo est un MUST pour expliquer le travail effectué au long du projet.

**Comment by NicolasGlassey** [comment]
![image](https://github.com/CPNV-ES-RIA2/LUIS/assets/5616312/3c320823-557c-44d2-a6d1-187ba30574ca)
